/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package solution.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum GameTypes { 
  TexasHoldem, Blackjack, PaiGow, FiveCardDraw  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GameTypes\",\"namespace\":\"solution.model\",\"symbols\":[\"TexasHoldem\",\"Blackjack\",\"PaiGow\",\"FiveCardDraw\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
