/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package solution.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Suit { 
  SPADE, HEART, DIAMOND, CLUB  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Suit\",\"namespace\":\"solution.model\",\"symbols\":[\"SPADE\",\"HEART\",\"DIAMOND\",\"CLUB\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
